module.exports = {
  darkMode: "class",
  content: ["./*.html", "./assets/scripts/*.js"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#536d5a",
        "on-secondary-fixed-variant": "#474744",
        "surface-dim": "#dbd9d9",
        outline: "#717783",
        "tertiary-fixed-dim": "#87dc2c",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#e4e2dd",
        "on-tertiary-fixed": "#0e2000",
        "surface-container-high": "#eae8e7",
        "outline-variant": "#c1c7d3",
        "tertiary-container": "#498300",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#f9ffeb",
        background: "#fbf9f8",
        "secondary-fixed-dim": "#c8c6c2",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#414751",
        "surface-container-highest": "#e4e2e2",
        "on-background": "#1b1c1c",
        "surface-variant": "#e4e2e2",
        "on-tertiary-fixed-variant": "#2a5000",
        "on-primary-container": "#fdfcff",
        "on-secondary-container": "#63635f",
        "on-primary-fixed": "#1f2a22",
        "inverse-surface": "#303030",
        "tertiary-fixed": "#a1fa49",
        surface: "#fbf9f8",
        "surface-container-low": "#f5f3f3",
        "surface-bright": "#fbf9f8",
        "primary-container": "#e8efe8",
        "on-surface": "#1b1c1c",
        "primary-fixed": "#e8efe8",
        primary: "#536d5a",
        "on-primary-fixed-variant": "#1f2a22",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f2f0f0",
        "error-container": "#ffdad6",
        "secondary-container": "#e1dfdb",
        "primary-fixed-dim": "#d9e4d9",
        tertiary: "#386800",
        "inverse-primary": "#d9e4d9",
        "surface-container": "#efeded",
        secondary: "#5e5e5b",
        "on-secondary-fixed": "#1b1c19",
        "on-primary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "gutter-card": "16px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-page": "20px",
      },
      fontFamily: {
        sans: [
          "Noto Sans SC Local",
          "Noto Sans SC",
          "Source Han Sans SC",
          "Source Han Sans CN",
          "PingFang SC",
          "Hiragino Sans GB",
          "Arial",
          "sans-serif",
        ],
        "body-lg": ["Noto Sans SC Local"],
        "label-md": ["Noto Sans SC Local"],
        "body-md": ["Noto Sans SC Local"],
        "headline-md": ["Noto Sans SC Local"],
        "headline-lg": ["Noto Sans SC Local"],
        "headline-lg-mobile": ["Noto Sans SC Local"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.5px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
      boxShadow: {
        soft: "0px 4px 20px rgba(0, 0, 0, 0.04)",
        float: "0px 8px 30px rgba(83, 109, 90, 0.12)",
      },
    },
  },
  plugins: [],
};
